config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # Оборачиваем корневые маршруты в devise_scope
  devise_scope :user do
    authenticated :user do
      root to: 'home_page#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: 'home_page#index'
  
  resources :zak_specs, only: [:index] do
    collection do
      get 'export_to_excel'
      get 'export_to_word'
    end
  end

  resources :obr_spec, only: [:index] do
    collection do
      get 'export_to_excel'
      get 'export_to_word'
    end
  end

  resources :new_zakazs do
    collection do
      get 'export_to_excel'
      get 'export_to_word'
    end
  end

  resources :obrashenies do
    collection do
      get 'export_to_excel'
      get 'export_to_word'
    end
  end


  get 'kl_obsh_sum_zak/index'
  get 'obsh_summa_zak/index'
  get 'po_max_dohod/index'
  get 'avg_vypoln_obr/index'
  get 'avg_vypoln_zak/index'

  resources :new_zakazs

  #root 'home_page#index'
  get 'home_page/backup', to: 'home_page#backup', as: :backup_home_page
  get 'home_page/restore', to: 'home_page#restore', as: :restore_home_page
  get 'home_page/index'
  get 'po/index'
  get 'avg_vypoln_zak/index'
  get 'avg_vypoln_obr/index'
  get 'po_max_dohod/index'
  get 'obsh_summa_zak/index'
  get 'kl_obsh_sum_zak/index'

  resources :obrashenies
  resources :new_zakazs
  resources :specialists
  resources :klients
  resources :pos

  post 'home/backup',  to: 'home_page#backup',  as: :db_backup
  post 'home/restore', to: 'home_page#restore', as: :db_restore

  # Добавляем маршруты для экспорта отчетов
  get 'po_max_dohod/export_to_excel', to: 'po_max_dohod#export_to_excel', as: :export_to_excel_po_max_dohod
  get 'po_max_dohod/export_to_word', to: 'po_max_dohod#export_to_word', as: :export_to_word_po_max_dohod

  get 'obsh_summa_zak/export_to_excel', to: 'obsh_summa_zak#export_to_excel', as: :export_to_excel_obsh_summa_zak
  get 'obsh_summa_zak/export_to_word', to: 'obsh_summa_zak#export_to_word', as: :export_to_word_obsh_summa_zak

  get 'kl_obsh_sum_zak/export_to_excel', to: 'kl_obsh_sum_zak#export_to_excel', as: :export_to_excel_kl_obsh_sum_zak
  get 'kl_obsh_sum_zak/export_to_word', to: 'kl_obsh_sum_zak#export_to_word', as: :export_to_word_kl_obsh_sum_zak

  get 'avg_vypoln_obr/export_to_excel', to: 'avg_vypoln_obr#export_to_excel', as: :export_to_excel_avg_vypoln_obr
  get 'avg_vypoln_obr/export_to_word', to: 'avg_vypoln_obr#export_to_word', as: :export_to_word_avg_vypoln_obr

  get 'avg_vypoln_zak/export_to_excel', to: 'avg_vypoln_zak#export_to_excel', as: :export_to_excel_avg_vypoln_zak
  get 'avg_vypoln_zak/export_to_word', to: 'avg_vypoln_zak#export_to_word', as: :export_to_word_avg_vypoln_zak


  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/zak_spec.rb
class ZakSpec < ApplicationRecord
end

app/controllers/zak_specs_controller.rb
class ZakSpecsController < ApplicationController
  require 'axlsx'
  include ActionView::Helpers::NumberHelper # Для number_to_currency в контроллере
  before_action :load_specialists, only: [:index]

  # GET /zak_specs
  # params[:specialist_id], params[:start_date], params[:end_date]
  def index
    @specialist = Specialist.find_by(id: params[:specialist_id])

    start_date = params[:start_date].presence || Date.today.beginning_of_month
    end_date   = params[:end_date].presence   || Date.today

    scope = NewZakaz.where(data_zak: start_date..end_date)
    scope = scope.where(specialist_id: @specialist.id) if @specialist

    @zak_specs = scope.order(:data_zak)
  end

  def export_to_excel
    @specialist = Specialist.find_by(id: params[:specialist_id])
    start_date = params[:start_date].presence || Date.today.beginning_of_month
    end_date = params[:end_date].presence || Date.today

    scope = NewZakaz.where(data_zak: start_date..end_date)
    scope = scope.where(specialist_id: @specialist.id) if @specialist
    zak_specs = scope.order(:data_zak)

    p = Axlsx::Package.new
    wb = p.workbook

    title_style = wb.styles.add_style(sz: 16, b: true, alignment: { horizontal: :center })
    header_style = wb.styles.add_style(bg_color: "F2F2F2", fg_color: "000000", sz: 12, b: true, alignment: { horizontal: :left }, border: { style: :thin, color: "000000" })
    cell_style = wb.styles.add_style(alignment: { horizontal: :left }, border: { style: :thin, color: "000000" })

    wb.add_worksheet(name: "Отчет") do |sheet|
      sheet.add_row ["Отчет о заказах, выполненных специалистом #{@specialist&.fio_spec} за период #{start_date} - #{end_date}"], style: title_style
      sheet.merge_cells("A1:J1")
      sheet.add_row [""]
      sheet.add_row ["ПО", "Версия ПО", "Наименование клиента", "Специалист", "Дата заказа", "Дата выполнения", "Стоимость ПО в год, ₽", "Срок аренды", "Стоимость заказа, ₽", "Документ установки"], style: header_style
      zak_specs.each do |z|
        po_name = z.po.try(:name_po) || '-'
        po_vers = z.po.try(:vers_po) || '-'
        klient_name = z.klient.try(:name_komp) || '-'
        specialist_name = z.specialist.try(:fio_spec) || '-'
        data_zak = z.data_zak
        data_vypoln = z.data_vypoln_zak
        stoimost_v_god = number_to_currency(z.stoimost_v_god, unit: '', separator: ',', delimiter: ' ')
        srok_arendy = z.srok_arendy
        stoimost_zak = number_to_currency(z.stoimost_zak, unit: '', separator: ',', delimiter: ' ')
        dok_path = z.dok_vypoln_zak_path.present? ? File.basename(z.dok_vypoln_zak_path) : '-'
        sheet.add_row [po_name, po_vers, klient_name, specialist_name, data_zak, data_vypoln, "#{stoimost_v_god}₽", srok_arendy, "#{stoimost_zak}₽", dok_path], style: cell_style
      end
      sheet.add_row [""]
      sheet.add_row ["", "", "", "", "", "", "", "", "Общее число выполненных заказов:", zak_specs.size], style: cell_style

      # Установка ширины столбцов для равномерности
      sheet.column_widths(20, 10, 25, 20, 10, 10, 15, 10, 15, 20)

      # Установка параметров страницы для размещения на одной странице
      sheet.page_setup.fit_to_width = 1
      sheet.page_setup.fit_to_height = 1
    end

    send_data p.to_stream.read, filename: "zak_specs_report.xlsx", type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  end

  def export_to_word
    @specialist = Specialist.find_by(id: params[:specialist_id])
    start_date = params[:start_date].presence || Date.today.beginning_of_month
    end_date = params[:end_date].presence || Date.today

    scope = NewZakaz.where(data_zak: start_date..end_date)
    scope = scope.where(specialist_id: @specialist.id) if @specialist
    zak_specs = scope.order(:data_zak)

    if zak_specs.empty?
      redirect_to zak_specs_path, alert: "Нет данных для выбранного периода."
      return
    end

    html_content = "\xEF\xBB\xBF"
    html_content += "<html><head><meta charset='UTF-8'></head><body>"
    html_content += "<h1>Отчет о заказах, выполненных специалистом #{@specialist&.fio_spec} за период #{start_date} - #{end_date}</h1>"
    html_content += "<table border='1' cellpadding='5' cellspacing='0' width='100%'>"
    html_content += "<colgroup>"
    html_content += "<col width='60'>" # ПО
    html_content += "<col width='30'>" # Версия ПО
    html_content += "<col width='100'>" # Наименование клиента
    html_content += "<col width='60'>" # Специалист
    html_content += "<col width='50'>" # Дата заказа
    html_content += "<col width='50'>" # Дата выполнения
    html_content += "<col width='60'>" # Стоимость ПО в год, ₽
    html_content += "<col width='40'>" # Срок аренды
    html_content += "<col width='60'>" # Стоимость заказа, ₽
    html_content += "<col width='80'>" # Документ установки
    html_content += "</colgroup>"
    html_content += "<tr>"
    ["ПО", "Версия ПО", "Наименование клиента", "Специалист", "Дата заказа", "Дата выполнения", "Стоимость ПО в год, ₽", "Срок аренды", "Стоимость заказа, ₽", "Документ установки"].each do |header|
      html_content += "<th style='font-size:8pt; word-break:break-all; overflow-wrap:break-word;'>#{header}</th>"
    end
    html_content += "</tr>"
    zak_specs.each do |z|
      po_name = z.po.try(:name_po) || '-'
      po_vers = z.po.try(:vers_po) || '-'
      klient_name = z.klient.try(:name_komp) || '-'
      specialist_name = z.specialist.try(:fio_spec) || '-'
      data_zak = z.data_zak
      data_vypoln = z.data_vypoln_zak
      stoimost_v_god = number_to_currency(z.stoimost_v_god, unit: '', separator: ',', delimiter: ' ')
      srok_arendy = z.srok_arendy
      stoimost_zak = number_to_currency(z.stoimost_zak, unit: '', separator: ',', delimiter: ' ')
      dok_path = z.dok_vypoln_zak_path.present? ? File.basename(z.dok_vypoln_zak_path) : '-'
      html_content += "<tr>"
      [po_name, po_vers, klient_name, specialist_name, data_zak, data_vypoln, "#{stoimost_v_god}₽", srok_arendy, "#{stoimost_zak}₽", dok_path].each do |cell|
        html_content += "<td style='font-size:8pt; word-break:break-all; overflow-wrap:break-word;'>#{cell}</td>"
      end
      html_content += "</tr>"
    end
    html_content += "</table>"
    html_content += "<p><strong>Общее число выполненных заказов: #{zak_specs.size}</strong></p>"
    html_content += "</body></html>"

    send_data html_content, filename: "zak_specs_report.doc", type: "application/msword", disposition: 'attachment'
  end

  private

  def load_specialists
    @specialists = Specialist.order(:fio_spec)
  end
end

app/helpers/zak_specs_helper.rb
module ZakSpecsHelper
end

app/views/zak_specs/_form.html.erb
<%= form_with(model: zak_spec) do |form| %>
  <% if zak_spec.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(zak_spec.errors.count, "error") %> prohibited this zak_spec from being saved:</h2>

      <ul>
        <% zak_spec.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/zak_specs/_zak_spec.html.erb
<div id="<%= dom_id zak_spec %>">
  <p>
    <strong>Name:</strong>
    <%= zak_spec.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= zak_spec.description %>
  </p>

</div>

app/views/zak_specs/edit.html.erb
<h1>Editing zak spec</h1>

<%= render "form", zak_spec: @zak_spec %>

<br>

<div>
  <%= link_to "Show this zak spec", @zak_spec %> |
  <%= link_to "Back to zak specs", zak_specs_path %>
</div>

app/views/zak_specs/index.html.erb
<h1>Отчёт о заказах, выполненных специалистом за период</h1>

<%= form_with url: zak_specs_path, method: :get, local: true do %>
  <div class="form-group">
    <label for="specialist_id">Выберите специалиста:</label>
    <%= select_tag :specialist_id,
          options_from_collection_for_select(@specialists, :id, :fio_spec, params[:specialist_id]),
          include_blank: true %>
  </div>
  <div class="form-group">
    <label for="start_date">Дата начала:</label>
    <%= date_field_tag :start_date, params[:start_date] %>
  </div>
  <div class="form-group">
    <label for="end_date">Дата окончания:</label>
    <%= date_field_tag :end_date, params[:end_date] %>
  </div>

  <% if @zak_specs.any? %>
    <table border="1" cellpadding="10" cellspacing="0"
           style="width: 100%; text-align: left; border-collapse: collapse;">
      <thead>
        <tr style="background-color: #f2f2f2;">
          <th>ПО</th>
          <th>Версия ПО</th>
          <th>Наименование клиента</th>
          <th>Специалист</th>
          <th>Дата заказа</th>
          <th>Дата выполнения</th>
          <th>Стоимость ПО в год, ₽</th>
          <th>Срок аренды</th>
          <th>Стоимость заказа, ₽</th>
          <th>Документ установки</th>
        </tr>
      </thead>
      <tbody>
        <% @zak_specs.each do |z| %>
          <tr>
            <td><%= z.po.try(:name_po) || '-' %></td>
            <td><%= z.po.try(:vers_po) || '-' %></td>
            <td><%= z.klient.try(:name_komp) || '-' %></td>
            <td><%= z.specialist.try(:fio_spec) || '-' %></td>
            <td><%= z.data_zak %></td>
            <td><%= z.data_vypoln_zak %></td>
            <td><%= number_to_currency(z.stoimost_v_god, unit: '', separator: ',', delimiter: ' ') %>₽</td>
            <td><%= z.srok_arendy %></td>
            <td><%= number_to_currency(z.stoimost_zak, unit: '', separator: ',', delimiter: ' ') %>₽</td>
            <td>
              <% if z.dok_vypoln_zak_path.present? %>
                <%= link_to File.basename(z.dok_vypoln_zak_path),
                            z.dok_vypoln_zak_path,
                            target: '_blank' %>
              <% else %>
                —
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div style="margin-bottom: 20px;"></div>
    <p><strong>Общее число выполненных заказов: <%= @zak_specs.size %></strong></p>
  <% elsif (params[:specialist_id].present? ||
             params[:start_date].present? ||
             params[:end_date].present?) %>
    <p class="section-title">За выбранный период у специалиста нет выполненных заказов.</p>
  <% end %>

  <div class="buttons-container">
    <%= button_tag 'Показать', type: 'submit',
                  class: "button-style", style: "margin-bottom: 0px;" %>
    <%= link_to 'Сбросить', zak_specs_path,
                class: "button-style" %>
    <% if @zak_specs.any? %>
      <%= link_to 'Экспорт в Excel', export_to_excel_zak_specs_path(specialist_id: params[:specialist_id], start_date: params[:start_date], end_date: params[:end_date]), class: "button-style" %>
      <%= link_to 'Экспорт в Word', export_to_word_zak_specs_path(specialist_id: params[:specialist_id], start_date: params[:start_date], end_date: params[:end_date]), class: "button-style" %>
    <% end %>
    <%= link_to 'Назад', root_path,
                class: "button-style" %>
  </div>
<% end %>

app/views/zak_specs/new.html.erb
<h1>New zak spec</h1>

<%= render "form", zak_spec: @zak_spec %>

<br>

<div>
  <%= link_to "Back to zak specs", zak_specs_path %>
</div>

app/views/zak_specs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @zak_spec %>

<div>
  <%= link_to "Edit this zak spec", edit_zak_spec_path(@zak_spec) %> |
  <%= link_to "Back to zak specs", zak_specs_path %>

  <%= button_to "Destroy this zak spec", @zak_spec, method: :delete %>
</div>